### ISSUE TITLE
Implement basic version of the tool

### ISSUE THREAD

**Issue by Bardin08** [Bardin08/moodle-grade-report-generator#2]
## Description

- [x] Add implement Moodle's Gradebook report parsing & interacting module (#1) 
- [x] Implement updating Moodle's Gradebook with a similar but updated `csv` report (#1)
- [x] Implement checking marks by each student on the console (#1)
- [x] Implement saving the report to the local machine (#1)

## ACC
- All following tasks have been completed and tested*

---

Required tests:
- Unit tests to cover the base logic of the app
- Integration tests
